# Generated by Django 4.2.30 on 2026-09-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(db_index=True, max_length=100)),
                ('person_name', models.CharField(max_length=255)),
                ('device_id', models.CharField(max_length=255)),
                ('allocation_status', models.CharField(max_length=50)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('access_group', models.CharField(blank=True, max_length=255, null=True)),
                ('allocation_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('person_id', models.CharField(db_index=True, max_length=100)),
                ('person_name', models.CharField(max_length=255)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_type', models.CharField(max_length=100)),
                ('verification_method', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('person_name', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('enrollment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('enrollment_date_time', models.DateTimeField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
